common/urls.py
from django import views
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
   path('signup/', views.signup, name='signup')
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import debug
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),  
    # path('', debug.default_urlconf),

    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'), #http://127.0.0.1:8000/pybo
    path('<int:question_id>/', views.detail, name='detail'), #http://127.0.0.1:8000/pybo/6
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),

    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
]

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
#Paginator 불러오기
from django.core.paginator import Paginator
from django.db.models import Q, Count

# Create your views here.
def index(request):
    #question_list = Question.objects.order_by('-create_date')

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '') #검색어
    so = request.GET.get('so', 'recent') #정렬기준

    #정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    if so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else: # recent
        question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  #제목 검색
            Q(content__icontains=kw) |  #내용 검색
            Q(answer__content__icontains=kw) | #답변 내용 검색
            Q(author__username__icontains=kw) #질문 글쓴이 검색
        ).distinct() #답변 중복 방지.(질문의 답변, )

        """
        SELECT DISTINCT Q.*  FROM PYBO_QUESTION Q
        LEFT JOIN PYBO_ANSWER A ON A.QUESTION_ID = Q.ID
        RIGHT JOIN CUSTOMER C ON C.ID = A.AUTHOR
        WHERE Q.SUBJECT LIKE '%KW%'
            OR Q.CONTENT LIKE '%KW%'
        """

    #쿼리셋으로 조회됨.
    paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기

    #get_page 메서드는 유효하지 않은 번호도 자동 처리.(999->마지막 페이지로 처리.)
    page_obj = paginator.get_page(page)

    current_page = page_obj.number
    start_index = max(current_page - 5, 1)
    end_index = min(current_page + 5, paginator.num_pages)
    page_range = range(start_index, end_index + 1)

    context = {'question_list': page_obj,
               'page_range':page_range,
               'kw':kw,
               'so':so
               }
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'jquery-3.7.1.min.js' %}" >
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" >
    <style>
        a{
            color: black;
        }
    </style>
    <title>Document</title>
</head>
<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <script src="{% static 'jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 네비게이션바 -->
    {% block content %}
    {% endblock%}
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                        {{ user.username }}(로그아웃)
                    </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>